# Generated by Django 4.1.13 on 2024-09-04 19:40

from django.db import migrations, models
import law_enforcement_experience.models.law_enforcement_experience


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoryCase",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "id",
                    models.CharField(
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        verbose_name="主键id",
                    ),
                ),
                ("crime", models.CharField(max_length=1024, verbose_name="违法行为")),
                (
                    "crime_vector",
                    law_enforcement_experience.models.law_enforcement_experience.VectorField(
                        verbose_name="违法行为(向量)"
                    ),
                ),
                (
                    "regulation",
                    models.CharField(
                        max_length=512, null=True, verbose_name="涉嫌违反法律条文"
                    ),
                ),
                (
                    "decision",
                    models.CharField(max_length=512, null=True, verbose_name="作出决定依据"),
                ),
                (
                    "decision_basis",
                    models.CharField(max_length=512, null=True, verbose_name="建议行政决定"),
                ),
            ],
            options={
                "db_table": "law_history_case",
            },
        ),
        migrations.CreateModel(
            name="StandardCase",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "id",
                    models.CharField(
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        verbose_name="主键id",
                    ),
                ),
                (
                    "hazard_category",
                    models.CharField(max_length=128, verbose_name="隐患项分类名称"),
                ),
                (
                    "illegal_content",
                    models.CharField(max_length=1024, verbose_name="违法违规内容"),
                ),
                (
                    "illegal_content_vector",
                    law_enforcement_experience.models.law_enforcement_experience.VectorField(
                        verbose_name="违法违规内容(向量)"
                    ),
                ),
                (
                    "recognition_basis",
                    models.CharField(max_length=512, null=True, verbose_name="认定依据"),
                ),
                (
                    "site_basis",
                    models.CharField(max_length=512, null=True, verbose_name="现场处理决定"),
                ),
                (
                    "administrative_penalty_description",
                    models.CharField(
                        max_length=512, null=True, verbose_name="行政处罚决定描述"
                    ),
                ),
                (
                    "administrative_penalty_basis",
                    models.CharField(max_length=512, null=True, verbose_name="行政处罚依据"),
                ),
            ],
            options={
                "db_table": "law_standard_case",
            },
        ),
    ]
