# Generated by Django 4.1.13 on 2024-09-05 18:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dataset", "0006_alter_dataset_doc_type"),
        ("law_enforcement_experience", "0002_historycase_dataset_standardcase_dataset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historycase",
            name="id",
            field=models.CharField(
                default=uuid.uuid1,
                max_length=128,
                primary_key=True,
                serialize=False,
                verbose_name="主键id",
            ),
        ),
        migrations.AlterField(
            model_name="standardcase",
            name="id",
            field=models.CharField(
                default=uuid.uuid1,
                max_length=128,
                primary_key=True,
                serialize=False,
                verbose_name="主键id",
            ),
        ),
        migrations.CreateModel(
            name="CaseFieldNameMapping",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid1,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        verbose_name="主键id",
                    ),
                ),
                ("field", models.CharField(max_length=128, verbose_name="字段")),
                ("name", models.CharField(max_length=128, verbose_name="字段的中文名")),
                (
                    "dataset",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dataset.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "law_case_field_name_mapping",
            },
        ),
    ]
