# Generated by Django 4.1.13 on 2024-09-05 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dataset", "0006_alter_dataset_doc_type"),
        (
            "law_enforcement_experience",
            "0003_alter_historycase_id_alter_standardcase_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CaseFieldNameMapping",
            new_name="FieldNameMapping",
        ),
        migrations.AlterModelTable(
            name="fieldnamemapping",
            table="dataset_field_name_mapping",
        ),
    ]
