# Generated by Django 4.1.13 on 2024-09-06 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dataset", "0006_alter_dataset_doc_type"),
        (
            "law_enforcement_experience",
            "0004_rename_casefieldnamemapping_fieldnamemapping_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetTableMapping",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid1,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        verbose_name="主键id",
                    ),
                ),
                ("table_name", models.CharField(max_length=128, verbose_name="表名")),
                (
                    "dataset",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dataset.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "dataset_table_mapping",
            },
        ),
    ]
