# Generated by Django 4.1.13 on 2024-05-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0004_applicationaccesstoken_show_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="main_account",
            field=models.CharField(default="", max_length=256, verbose_name="煤矿用户账号"),
        ),
    ]
