# Generated by Django 4.1.13 on 2024-06-04 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0005_chat_main_account"),
        ("application", "0007_alter_application_prologue"),
    ]

    operations = []
